return {
  ["hagen"] = {
    author = "Hans Hagen",
    category = "article",
    issn = "1234-5678",
    issue = "3",
    journal = "MyJournal",
    month = "8",
    pages = "123--126",
    title = "Who knows nothing?",
    volume = "1",
    year = "2013",
  },
  ["hagen2"] = {
    author = "Hans Hagen2",
    category = "article",
    issn = "1234-5678",
    issue = "3",
    journal = "MyJournal",
    month = "8",
    pages = "123--126",
    title = "Who knows nothing?",
    volume = "1",
    year = "2013",
  },
}
